# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plate_recognizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plate_recognizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16plate_recognizer.proto\x12\x05plate\"A\n\x0cPlateRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\"\n\x04mode\x18\x02 \x01(\x0e\x32\x14.plate.RecognizeMode\"Z\n\rPlateResponse\x12\x14\n\x0cplate_number\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x02\x12\x0e\n\x06height\x18\x05 \x01(\x02*G\n\rRecognizeMode\x12\r\n\tMODE_FULL\x10\x00\x12\x14\n\x10MODE_DETECT_ONLY\x10\x01\x12\x11\n\rMODE_OCR_ONLY\x10\x02\x32I\n\x0fPlateRecognizer\x12\x36\n\tRecognize\x12\x13.plate.PlateRequest\x1a\x14.plate.PlateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plate_recognizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNIZEMODE']._serialized_start=192
  _globals['_RECOGNIZEMODE']._serialized_end=263
  _globals['_PLATEREQUEST']._serialized_start=33
  _globals['_PLATEREQUEST']._serialized_end=98
  _globals['_PLATERESPONSE']._serialized_start=100
  _globals['_PLATERESPONSE']._serialized_end=190
  _globals['_PLATERECOGNIZER']._serialized_start=265
  _globals['_PLATERECOGNIZER']._serialized_end=338
# @@protoc_insertion_point(module_scope)
